### ISSUE TITLE
Build output is mixed with the sources

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2023_Analysis_CompoundUnits#3]
E.g., [here](https://github.com/MATF-Software-Verification/2023_Analysis_Igra_memorije/tree/main/unit_tests/petar_unit_test) but there is also a build folder [here](https://github.com/MATF-Software-Verification/2023_Analysis_Igra_memorije/tree/main/unit_tests/build-petar_unit_test-Desktop-Debug). These need to be tidied, if a student tomorrow looks at this, they won't be able to know which folder to look at.

**Comment by PosteruOle** [comment]
I hope I solved those problems. I added README.md file for unit_tests folder and I rename folders within unit_tests folder. Hope it looks better now.
