### ISSUE TITLE
Add a submodule for the original project

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2023_Analysis_CompoundUnits#6]
- [x] Instead of adding the entire project as a subdirectory, add a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

**Comment by PosteruOle** [comment]
I added project as a submodule on my private repository (here is the link https://github.com/PosteruOle/2023_Analysis_Compound_Unit), but I have some difficulties when adding a submodule on a new repository. Do you have some idea how can I resolve it?

**Comment by PosteruOle** [comment]
Done! Creating a new branch and merging it into the main branch solved a problem.
